package dashboard.command;

import dashboard.cli.ConsoleMessage;
import dashboard.game.GameContext;

/**
 * A Command is any action that can be asked to be executed by the 
 * user to the Football Scoring Dashboard application.
 * 
 * @author sebastienhamel
 *
 */
public interface Command {

	/**
	 * The execute method takes the GameContext and execute the actions
	 * associated with the Command instance. 
	 * 
	 * @param context
	 * @return The ConsoleMessage generated by the execute(..) method of the Command instance.
	 */
	public ConsoleMessage execute(GameContext context);
}
